### PR TITLE
Double quotes to single quote to avoid messing up c# string

### PR DESCRIPTION
**Pull request by KevM**
WIth `fubu new --app` out of the box for me the generated project fails to build due to unescaped quotes.

### CODE REVIEW

**Comment by jeremydmiller** [comment]
I fixed it while I was in the code yesterday after this PR came in.  Thanks for calling this out though.

**Comment by KevM** [comment]
Thanks for missing an added contributor on Fubu,

**Comment by jeremydmiller** [comment]
Kevin,

C'mon man, seriously?  All it came down to was that it was easier to reproduce your fix _after looking right at your PR_ than it was for me to do the PR merge dance.
- Jeremy

**Comment by KevM** [comment]
Gotcha just letting you know how contributors feel to have their commits squished.

**Pull request closed without merging**
